/*
 *
  ***** BEGIN LICENSE BLOCK *****

  Copyright (C) 2009-2016 Olof Hagsand and Benny Holmgren
  Copyright (C) 2017-2019 Olof Hagsand
  Copyright (C) 2020-2022 Olof Hagsand and Rubicon Communications, LLC(Netgate)

  This file is part of CLIXON.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  Alternatively, the contents of this file may be used under the terms of
  the GNU General Public License Version 3 or later (the "GPL"),
  in which case the provisions of the GPL are applicable instead
  of those above. If you wish to allow use of your version of this file only
  under the terms of the GPL, and not to allow others to
  use your version of this file under the terms of Apache License version 2,
  indicate your decision by deleting the provisions above and replace them with
  the  notice and other provisions required by the GPL. If you do not delete
  the provisions above, a recipient may use your version of this file under
  the terms of any one of the Apache License version 2 or the GPL.

  ***** END LICENSE BLOCK *****

 * Compare XML trees
 */

#ifdef HAVE_CONFIG_H
#include "clixon_config.h" /* generated by config & autoconf */
#endif

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <limits.h>
#include <stdint.h>
#include <syslog.h>
#include <fcntl.h>
#include <signal.h>
#include <assert.h>
#include <sys/time.h>
#include <sys/stat.h>

/* cligen */
#include <cligen/cligen.h>

/* clixon */
#include "clixon/clixon.h"

/* Command line options passed to getopt(3) */
#define UTIL_XML_OPTS "hD:l:f:i:o:y:Y:u"

static int
validate_tree(clixon_handle h,
              cxobj        *xt,
              yang_stmt    *yspec)
{
    int    retval = -1;
    int    ret;
    cxobj *xerr = NULL; /* malloced must be freed */
    cbuf         *cbret = NULL;

    /* should already be populated */
    /* Add default values */
    if (xml_default_recurse(xt, 0, 0) < 0)
        goto done;
    if (xml_apply(xt, -1, xml_sort_verify, h) < 0)
        clixon_log(h, LOG_NOTICE, "%s: sort verify failed", __FUNCTION__);
    if ((ret = xml_yang_validate_all_top(h, xt, &xerr)) < 0)
        goto done;
    if (ret > 0 && (ret = xml_yang_validate_add(h, xt, &xerr)) < 0)
        goto done;
    if (ret == 0){
        if ((cbret = cbuf_new()) ==NULL){
            clixon_err(OE_XML, errno, "cbuf_new");
            goto done;
        }
        if (netconf_err2cb(h, xerr, cbret) < 0)
            goto done;
        fprintf(stderr, "xml validation error: %s\n", cbuf_get(cbret));
        goto done;
    }
    retval = 0;
 done:
    if (cbret)
        cbuf_free(cbret);
    if (xerr)
        xml_free(xerr);
    return retval;
}

#if 1 /* Should be in clixon lib */
/*! Check single node equivalence
 *
 * @param[in]  x0   XML object 0
 * @param[in]  x1   XML object 1
 * @param[out] eq   0: equal, <0: x0 < x1, >0: x0 > x1
 * @retval     0    OK
 * @retval    -1    Error
 */
static int
xml_node_same(cxobj *x0,
              cxobj *x1,
              int   *obj)
{
    int        retval = -1; /* Not equal */
    yang_stmt *y0;
    yang_stmt *y1;
    int        ret;

    if (x0 == NULL && x1 == NULL){
        *obj = 0;
        goto ok;
    }
    else if (x0 == NULL){
        *obj = 1;
        goto ok;
    }
    else if (x1 == NULL){
        *obj = -1;
        goto ok;
    }
    if ((ret = xml_cmp(x0, x1, 0, 0, NULL)) != 0){
        *obj = ret;
        goto ok;
    }
    /* Same object */
    y0 = xml_spec(x0);
    y1 = xml_spec(x1);
    assert(y0 && y1);
    if (y0 != y1) /* choice */{
        *obj = 1;
        goto done;
    }
    *obj = 0;
 ok:
    retval = 0;
 done:
    return retval;
}

/*! Check single node equivalence
 *
 * @param[in]  x0     XML object 0
 * @param[in]  x1     XML object 1
 * @param[out] eq     0: Object is leaf and changed value, else equal or not leaf
 * @param[out] value0 If eq=0, value in x0
 * @param[out] value1 If eq=0, value in x1
 * @retval     0      OK
 * @retval    -1      Error
 */
static int
xml_node_eq(cxobj *x0,
            cxobj *x1,
            int   *eq,
            char **value0,
            char **value1)
{
    int        retval = -1; /* Not equal */
    yang_stmt *y0;
    yang_stmt *y1;
    char      *b0;
    char      *b1;

    assert(x0 && x1);
    /* Same object */
    y0 = xml_spec(x0);
    y1 = xml_spec(x1);
    assert(y0 && y1);
    if (yang_keyword_get(y0) == Y_LEAF){
        b0 = xml_body(x0);
        b1 = xml_body(x1);
        if (b0 == NULL && b1 == NULL)
            *eq = 1;
        else if (b0 == NULL || b1 == NULL
                 || strcmp(b0, b1) != 0
                 ){
            *eq = 0;
            if (value0)
                *value0 = b0;
            if (value1)
                *value1 = b1;
        }
        else
            *eq = 1;
    }
    else
        *eq = 1;
    retval = 0;
    // done:
    return retval;
}

/*! Check if conflict when rebasing tree x0 to x2 for x1
 *
 * x0 is original base candidate datastore
 * x1 is modified candidate datastore
 * x2 Current datastore, the new base
 * This function checks issues with replacing the candidate datastore (x1) with the
 * current running config (x2) and replaying the the config changes (x0->x1)
 * against it.
 * Number of conflicts are returned, and the nature of each conflict is logged with
 * debug flag xml (start with -D xml)
                           update commit
          +--------------------+---+------> private candidate 1
         /                  x1 ^    \
     x0 /  edit-config     x2 /      ⌄
   +---+--------+--------+---+-------+----> running configuration
    edit-config  \       ^
                  \     /
                   +---+------------------> private candidate 2
                    commit

 * @param[in]  h        Clixon handle
 * @param[in]  x0       Original
 * @param[in]  x1       Candidate
 * @param[in]  x2       Running
 * @param[out] conflict Set to number of conflicts, if any
 * @retval     0        OK
 * @retval    -1        Error
 * @see xml_tree_equal
 * @see xml_diff
 */
int
xml_rebase_check(clixon_handle h,
                 cxobj        *x0,
                 cxobj        *x1,
                 cxobj        *x2,
                 int          *conflict)
{
    int    retval = -1;
    cxobj *x0c;
    cxobj *x1c;
    cxobj *x2c;
    int    same10;
    int    same20;
    int    same12;
    char  *xpath0 = NULL;
    char  *xpath1 = NULL;
    char  *xpath2 = NULL;
    int    eq1;
    int    eq2;
    char  *value0;
    char  *value1;

    x0c = x1c = x2c = NULL;
    x0c = xml_child_each(x0, x0c, CX_ELMNT);
    x1c = xml_child_each(x1, x1c, CX_ELMNT);
    x2c = xml_child_each(x2, x2c, CX_ELMNT);
    while (x0c != NULL && x1c != NULL && x2c != NULL){
        if (x0c && xml2xpath(x0c, NULL, 0, 0, &xpath0) < 0)
            goto done;
        if (x1c && xml2xpath(x1c, NULL, 0, 0, &xpath1) < 0)
            goto done;
        if (x2c && xml2xpath(x2c, NULL, 0, 0, &xpath2) < 0)
            goto done;
        if (xml_node_same(x1c, x0c, &same10) < 0)
            goto done;
        if (xml_node_same(x2c, x0c, &same20) < 0)
            goto done;
        if (xml_node_same(x1c, x2c, &same12) < 0)
            goto done;
        clixon_debug(CLIXON_DBG_XML, "%d %d %d\n", same10, same20, same12);
        eq1 = 0;
        if (same10 < 0){ /* New in x1c */
            if (same20 < 0){
                if (same12 == 0){
                    if (xml_tree_equal(x1c, x2c) != 0){
                        clixon_debug(CLIXON_DBG_XML, "Conflict %d: x0:%s x1:%s x2:%s Both added unequal object",
                                (*conflict+1), xpath0, xpath1, xpath2);
                        (*conflict)++;
                    }
                }
                x2c = xml_child_each(x2, x2c, CX_ELMNT);
            }
            x1c = xml_child_each(x1, x1c, CX_ELMNT);
            goto next;
        }
        else if (same10 == 0){
            if (same20 < 0){
                x1c = xml_child_each(x1, x1c, CX_ELMNT);
                goto next;
            }
            else if (same20 == 0){
                /* Same node, has value changed? */
                eq1 = eq2 = 0;
                if (xml_node_eq(x1c, x0c, &eq1, &value1, &value0) < 0)
                    goto done;
                if (eq1 == 0){
                    if (xml_node_eq(x2c, x0c, &eq2, NULL, NULL) < 0)
                        goto done;
                    if (eq2 == 0){
                        clixon_debug(CLIXON_DBG_XML, "Conflict %d: x0:%s x1:%s x2:%s x1 and x2 both changed value\n",
                                (*conflict+1), xpath0, xpath1, xpath2);
                        (*conflict)++;
                    }
                }

            }
            else if (same20 > 0){
                /* x2c deleted -> Conflict if to x1-x0 */
                if (xml_tree_equal(x0c, x1c) != 0){
                    clixon_debug(CLIXON_DBG_XML, "Conflict %d: x0:%s x1:%s x2:%s x2c removed",
                            (*conflict+1), xpath0, xpath1, xpath2);
                    (*conflict)++;
                }
                x0c = xml_child_each(x0, x0c, CX_ELMNT);
                x1c = xml_child_each(x1, x1c, CX_ELMNT);
                goto next;
            }
        }
        else if (same10 > 0){ /* Deleted x1c */
            if (same20 < 0){
                x2c = xml_child_each(x2, x2c, CX_ELMNT);
                goto next;
            }
            else if (same20 == 0){
                if (xml_tree_equal(x0c, x2c) != 0){
                    clixon_debug(CLIXON_DBG_XML, "Conflict %d: x0:%s x1:%s x2:%s x1c removed",
                            (*conflict+1), xpath0, xpath1, xpath2);
                    (*conflict)++;
                }
                x0c = xml_child_each(x0, x0c, CX_ELMNT);
                x2c = xml_child_each(x2, x2c, CX_ELMNT);
                goto next;
            }
        }
        assert(same10 == same20 && same10 == same12);
        if (xml_rebase_check(h, x0c, x1c, x2c, conflict) < 0)
            goto done;
        x0c = xml_child_each(x0, x0c, CX_ELMNT);
        x1c = xml_child_each(x1, x1c, CX_ELMNT);
        x2c = xml_child_each(x2, x2c, CX_ELMNT);
    next:
        if (xpath0){
            free(xpath0);
            xpath0 = NULL;
        }
        if (xpath1){
            free(xpath1);
            xpath1 = NULL;
        }
        if (xpath2){
            free(xpath2);
            xpath2 = NULL;
        }
    }
    retval = 0;
 done:
    if (xpath0)
        free(xpath0);
    if (xpath1)
        free(xpath1);
    if (xpath2)
        free(xpath2);
    return retval;
}
#endif

static int
usage(char *argv0)
{
    fprintf(stderr, "Compare XML trees\n"
            "usage:%s [options] where options are\n"
            "\t-h \t\tHelp\n"
            "\t-D <level> \tDebug\n"
            "\t-l <s|e|o> \tLog on (s)yslog, std(e)rr, std(o)ut (stderr is default)\n"
            "\t-f <file>\tinput file (can be 2 or 3)\n"
            "\t-i <format>\tInput file format: (xml|json|text) default:xml\n"
            "\t-o <format>\tOutput format: (xml|json|text) default:xml\n"
            "\t-y <filename> \tYang filename or dir (load all files)\n"
            "\t-Y <dir> \tYang dirs (can be several)\n"
            "\t-u \t\tTreat unknown XML as anydata\n"
            ,
            argv0);
    exit(0);
}

int
main(int    argc,
     char **argv)
{
    int              retval = -1;
    cbuf            *cb = cbuf_new();
    int              c;
    int              logdst = CLIXON_LOG_STDERR;
    char            *yang_file_dir = NULL;
    yang_stmt       *yspec = NULL;
    cxobj           *xerr = NULL; /* malloced must be freed */
    clixon_handle    h;
    struct stat      st;
    cxobj           *xcfg = NULL;
    cbuf            *cbret = NULL;
    cvec            *nsc = NULL;
    int              dbg = 0;
    char           **filenames = NULL;
    FILE           **fps = NULL;
    cxobj          **xts = NULL;
    int              fnr = 0;
    enum format_enum format_in = FORMAT_XML;
    enum format_enum format_out = FORMAT_XML;
    int              i;
    int              conflict;
    int              ret;
    
    /* Initialize clixon handle */
    if ((h = clixon_handle_init()) == NULL)
        goto done;
    /* In the startup, logs to stderr & debug flag set later */
    clixon_log_init(h, __FILE__, LOG_INFO, CLIXON_LOG_STDERR);

    if ((xcfg = xml_new("clixon-config", NULL, CX_ELMNT)) == NULL)
        goto done;
    if (clicon_conf_xml_set(h, xcfg) < 0)
        goto done;

    optind = 1;
    opterr = 0;
    while ((c = getopt(argc, argv, UTIL_XML_OPTS)) != -1)
        switch (c) {
        case 'h':
            usage(argv[0]);
            break;
        case 'D':
            if (sscanf(optarg, "%d", &dbg) != 1)
                usage(argv[0]);
            break;
        case 'l': /* Log destination: s|e|o|f */
            if ((logdst = clixon_log_opt(optarg[0])) < 0)
                usage(argv[0]);
            break;
        case 'f':
            if ((filenames = realloc(filenames, sizeof(char*)*(fnr+1))) == NULL){
                clixon_err(OE_UNIX, errno, "realloc");
                goto done;
            }
            if ((fps = realloc(fps, sizeof(FILE*)*(fnr+1))) == NULL){
                clixon_err(OE_UNIX, errno, "realloc");
                goto done;
            }
            if ((xts = realloc(xts, sizeof(cxobj*)*(fnr+1))) == NULL){
                clixon_err(OE_UNIX, errno, "realloc");
                goto done;
            }
            filenames[fnr] = optarg;
            fps[fnr] = NULL;
            xts[fnr] = NULL;
            fnr++;
            break;
        case 'i': /* input format */
            if ((int)(format_in = format_str2int(optarg)) < 0){
                clixon_err(OE_CFG, 0, "No such format %s", optarg);
                goto done;
            }
            break;
        case 'o': /* output format */
            if ((int)(format_out = format_str2int(optarg)) < 0){
                clixon_err(OE_CFG, 0, "No such format %s", optarg);
                goto done;
            }
            break;
        case 'y':
            yang_file_dir = optarg;
            break;
        case 'Y':
            if (clicon_option_add(h, "CLICON_YANG_DIR", optarg) < 0)
                goto done;
            break;
        case 'u':
            if (clicon_option_bool_set(h, "CLICON_YANG_UNKNOWN_ANYDATA", 1) < 0)
                goto done;
            xml_bind_yang_unknown_anydata(1);
            break;
        default:
            usage(argv[0]);
            break;
        }
    if (fnr < 2 || fnr > 3){
        fprintf(stderr, "Error: Two or three -f <input-files> required\n");
        goto done;
    }
    if (yang_file_dir == NULL){
        fprintf(stderr, "Error: -y required\n");
        goto done;
    }
    clixon_log_init(h, __FILE__, dbg?LOG_DEBUG:LOG_INFO, logdst);
    clixon_debug_init(h, dbg);
    if (yang_init(h) < 0)
        goto done;
    /* 1. Parse yang */
    if (yang_file_dir){
        if ((yspec = yspec_new(h, YANG_DATA_TOP)) == NULL)
            goto done;
        if (stat(yang_file_dir, &st) < 0){
            clixon_err(OE_YANG, errno, "%s not found", yang_file_dir);
            goto done;
        }
        if (S_ISDIR(st.st_mode)){
            if (yang_spec_load_dir(h, yang_file_dir, yspec) < 0)
                goto done;
        }
        else{
            if (yang_spec_parse_file(h, yang_file_dir, yspec) < 0)
                goto done;
        }
    }
    /* 2. Open files */
    for (i=0; i<fnr; i++){
        if ((fps[i] = fopen(filenames[i], "r")) == NULL){
            clixon_err(OE_YANG, errno, "open(%s)", filenames[i]);
            goto done;
        }
        /* 3. Parse data according to format */
        switch (format_in){
        case FORMAT_XML:    
            if ((ret = clixon_xml_parse_file(fps[i],
                                             YB_MODULE,
                                             yspec,
                                            &xts[i],
                                            &xerr)) < 0)
                goto done;
            break;
        case FORMAT_TEXT:
            if ((ret = clixon_text_syntax_parse_file(fps[i],
                                                     YB_MODULE,
                                                     yspec,
                                                     &xts[i],
                                                     &xerr)) < 0)
                goto done;
            break;
        case FORMAT_JSON:
            if ((ret = clixon_json_parse_file(fps[i],
                                              1,
                                              YB_MODULE,
                                              yspec,
                                              &xts[i],
                                              &xerr)) < 0)
                goto done;
        default:
            clixon_err(OE_XML, 0, "Unsupported format");
            goto done;
            break;
            
        }
        if (ret == 0){
            clixon_err_netconf(h, OE_XML, 0, xerr, "util_xml");
            goto done;
        }
        /* 3. Validate data */
        if (validate_tree(h, xts[i], yspec) < 0)
            goto done;
    }
    if (fnr == 2){
        ret = xml_tree_equal(xts[0], xts[1]);
        if (ret == 0)
            fprintf(stderr, "x0 = x1\n");
        else
            fprintf(stderr, "x0 != x1\n");
    }
    else if (fnr == 3){
        conflict = 0;
        if (xml_rebase_check(h, xts[0], xts[1], xts[2], &conflict) < 0)
            goto done;
        if (conflict == 0)
            fprintf(stdout, "ok\n");
        else
            fprintf(stdout, "conflict\n");
    }
    retval = 0;
 done:
    yang_exit(h);
    if (filenames)
        free(filenames);
    if (fps){
        for (i=0; i<fnr; i++){
            if (fps[i])
                fclose(fps[i]);
        }
        free(fps);
    }
    if (xts){
        for (i=0; i<fnr; i++){
            if (xts[i])
                xml_free(xts[i]);
        }
        free(xts);
    }
    if (nsc)
        cvec_free(nsc);
    if (cbret)
        cbuf_free(cbret);
    if (xcfg)
        xml_free(xcfg);
    if (xerr)
        xml_free(xerr);
    if (cb)
        cbuf_free(cb);
    if (h)
        clixon_handle_exit(h);
    return retval;
}
