/*
 *
  ***** BEGIN LICENSE BLOCK *****

  Copyright (C) 2025 Olof Hagsand and Rubicon Communications, LLC(Netgate)

  This file is part of CLIXON.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  Alternatively, the contents of this file may be used under the terms of
  the GNU General Public License Version 3 or later (the "GPL"),
  in which case the provisions of the GPL are applicable instead
  of those above. If you wish to allow use of your version of this file only
  under the terms of the GPL, and not to allow others to
  use your version of this file under the terms of Apache License version 2,
  indicate your decision by deleting the provisions above and replace them with
  the  notice and other provisions required by the GPL. If you do not delete
  the provisions above, a recipient may use your version of this file under
  the terms of any one of the Apache License version 2 or the GPL.

  ***** END LICENSE BLOCK *****

 * Compare XML trees
 * Test uses three trees:
 * x0 - Orig
 * x1 - Candidate
 * x2 - Running
 */

#ifdef HAVE_CONFIG_H
#include "clixon_config.h" /* generated by config & autoconf */
#endif

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <limits.h>
#include <stdint.h>
#include <syslog.h>
#include <fcntl.h>
#include <signal.h>
#include <assert.h>
#include <sys/time.h>
#include <sys/stat.h>

/* cligen */
#include <cligen/cligen.h>

/* clixon */
#include "clixon/clixon.h"

/* Command line options passed to getopt(3) */
#define UTIL_XML_OPTS "hD:l:f:i:o:y:Y:u"

static int
validate_tree(clixon_handle h,
              cxobj        *xt,
              yang_stmt    *yspec)
{
    int    retval = -1;
    int    ret;
    cxobj *xerr = NULL; /* malloced must be freed */
    cbuf         *cbret = NULL;

    /* should already be populated */
    /* Add default values */
    if (xml_default_recurse(xt, 0, 0) < 0)
        goto done;
    if (xml_apply(xt, -1, xml_sort_verify, h) < 0)
        clixon_log(h, LOG_NOTICE, "%s: sort verify failed", __FUNCTION__);
    if ((ret = xml_yang_validate_all_top(h, xt, &xerr)) < 0)
        goto done;
    if (ret > 0 && (ret = xml_yang_validate_add(h, xt, &xerr)) < 0)
        goto done;
    if (ret == 0){
        if ((cbret = cbuf_new()) ==NULL){
            clixon_err(OE_XML, errno, "cbuf_new");
            goto done;
        }
        if (netconf_err2cb(h, xerr, cbret) < 0)
            goto done;
        fprintf(stderr, "xml validation error: %s\n", cbuf_get(cbret));
        goto done;
    }
    retval = 0;
 done:
    if (cbret)
        cbuf_free(cbret);
    if (xerr)
        xml_free(xerr);
    return retval;
}

static int
usage(char *argv0)
{
    fprintf(stderr, "Compare XML trees\n"
            "usage:%s [options] where options are\n"
            "\t-h \t\tHelp\n"
            "\t-D <level> \tDebug\n"
            "\t-l <s|e|o> \tLog on (s)yslog, std(e)rr, std(o)ut (stderr is default)\n"
            "\t-f <file>\tinput file (can be 2 or 3)\n"
            "\t-i <format>\tInput file format: (xml|json|text) default:xml\n"
            "\t-o <format>\tOutput format: (xml|json|text) default:xml\n"
            "\t-y <filename> \tYang filename or dir (load all files)\n"
            "\t-Y <dir> \tYang dirs (can be several)\n"
            "\t-u \t\tTreat unknown XML as anydata\n"
            ,
            argv0);
    exit(0);
}

int
main(int    argc,
     char **argv)
{
    int              retval = -1;
    cbuf            *cb = cbuf_new();
    int              c;
    int              logdst = CLIXON_LOG_STDERR;
    char            *yang_file_dir = NULL;
    yang_stmt       *yspec = NULL;
    cxobj           *xerr = NULL; /* malloced must be freed */
    clixon_handle    h;
    struct stat      st;
    cxobj           *xcfg = NULL;
    cbuf            *cbret = NULL;
    cvec            *nsc = NULL;
    int              dbg = 0;
    char           **filenames = NULL;
    FILE           **fps = NULL;
    cxobj          **xts = NULL;
    int              fnr = 0;
    enum format_enum format_in = FORMAT_XML;
    enum format_enum format_out = FORMAT_XML;
    int              i;
    int              conflict;
    int              ret;
    
    /* Initialize clixon handle */
    if ((h = clixon_handle_init()) == NULL)
        goto done;
    /* In the startup, logs to stderr & debug flag set later */
    clixon_log_init(h, __FILE__, LOG_INFO, CLIXON_LOG_STDERR);

    if ((xcfg = xml_new("clixon-config", NULL, CX_ELMNT)) == NULL)
        goto done;
    if (clicon_conf_xml_set(h, xcfg) < 0)
        goto done;

    optind = 1;
    opterr = 0;
    while ((c = getopt(argc, argv, UTIL_XML_OPTS)) != -1)
        switch (c) {
        case 'h':
            usage(argv[0]);
            break;
        case 'D':
            if (sscanf(optarg, "%d", &dbg) != 1)
                usage(argv[0]);
            break;
        case 'l': /* Log destination: s|e|o|f */
            if ((logdst = clixon_log_opt(optarg[0])) < 0)
                usage(argv[0]);
            break;
        case 'f':
            if ((filenames = realloc(filenames, sizeof(char*)*(fnr+1))) == NULL){
                clixon_err(OE_UNIX, errno, "realloc");
                goto done;
            }
            if ((fps = realloc(fps, sizeof(FILE*)*(fnr+1))) == NULL){
                clixon_err(OE_UNIX, errno, "realloc");
                goto done;
            }
            if ((xts = realloc(xts, sizeof(cxobj*)*(fnr+1))) == NULL){
                clixon_err(OE_UNIX, errno, "realloc");
                goto done;
            }
            filenames[fnr] = optarg;
            fps[fnr] = NULL;
            xts[fnr] = NULL;
            fnr++;
            break;
        case 'i': /* input format */
            if ((int)(format_in = format_str2int(optarg)) < 0){
                clixon_err(OE_CFG, 0, "No such format %s", optarg);
                goto done;
            }
            break;
        case 'o': /* output format */
            if ((int)(format_out = format_str2int(optarg)) < 0){
                clixon_err(OE_CFG, 0, "No such format %s", optarg);
                goto done;
            }
            break;
        case 'y':
            yang_file_dir = optarg;
            break;
        case 'Y':
            if (clicon_option_add(h, "CLICON_YANG_DIR", optarg) < 0)
                goto done;
            break;
        case 'u':
            if (clicon_option_bool_set(h, "CLICON_YANG_UNKNOWN_ANYDATA", 1) < 0)
                goto done;
            xml_bind_yang_unknown_anydata(1);
            break;
        default:
            usage(argv[0]);
            break;
        }
    if (fnr < 2 || fnr > 3){
        fprintf(stderr, "Error: Two or three -f <input-files> required\n");
        goto done;
    }
    if (yang_file_dir == NULL){
        fprintf(stderr, "Error: -y required\n");
        goto done;
    }
    clixon_log_init(h, __FILE__, dbg?LOG_DEBUG:LOG_INFO, logdst);
    clixon_debug_init(h, dbg);
    if (yang_init(h) < 0)
        goto done;
    /* 1. Parse yang */
    if (yang_file_dir){
        if ((yspec = yspec_new(h, YANG_DATA_TOP)) == NULL)
            goto done;
        if (stat(yang_file_dir, &st) < 0){
            clixon_err(OE_YANG, errno, "%s not found", yang_file_dir);
            goto done;
        }
        if (S_ISDIR(st.st_mode)){
            if (yang_spec_load_dir(h, yang_file_dir, yspec) < 0)
                goto done;
        }
        else{
            if (yang_spec_parse_file(h, yang_file_dir, yspec) < 0)
                goto done;
        }
    }
    /* 2. Open files */
    for (i=0; i<fnr; i++){
        if ((fps[i] = fopen(filenames[i], "r")) == NULL){
            clixon_err(OE_YANG, errno, "open(%s)", filenames[i]);
            goto done;
        }
        /* 3. Parse data according to format */
        switch (format_in){
        case FORMAT_XML:    
            if ((ret = clixon_xml_parse_file(fps[i],
                                             YB_MODULE,
                                             yspec,
                                            &xts[i],
                                            &xerr)) < 0)
                goto done;
            break;
        case FORMAT_TEXT:
            if ((ret = clixon_text_syntax_parse_file(fps[i],
                                                     YB_MODULE,
                                                     yspec,
                                                     &xts[i],
                                                     &xerr)) < 0)
                goto done;
            break;
        case FORMAT_JSON:
            if ((ret = clixon_json_parse_file(fps[i],
                                              1,
                                              YB_MODULE,
                                              yspec,
                                              &xts[i],
                                              &xerr)) < 0)
                goto done;
        default:
            clixon_err(OE_XML, 0, "Unsupported format");
            goto done;
            break;
            
        }
        if (ret == 0){
            clixon_err_netconf(h, OE_XML, 0, xerr, "util_xml");
            goto done;
        }
        /* 3. Validate data */
        if (validate_tree(h, xts[i], yspec) < 0)
            goto done;
    }
    if (fnr == 2){
        ret = xml_tree_equal(xts[0], xts[1]);
        if (ret == 0)
            fprintf(stderr, "x0 = x1\n");
        else
            fprintf(stderr, "x0 != x1\n");
    }
    else if (fnr == 3){
        conflict = 0;
        if (xml_rebase(h, xts[0], xts[1], xts[2], &conflict, NULL, NULL) < 0)
            goto done;
        if (conflict == 0)
            fprintf(stdout, "ok\n");
        else
            fprintf(stdout, "conflict\n");
    }
    retval = 0;
 done:
    yang_exit(h);
    if (filenames)
        free(filenames);
    if (fps){
        for (i=0; i<fnr; i++){
            if (fps[i])
                fclose(fps[i]);
        }
        free(fps);
    }
    if (xts){
        for (i=0; i<fnr; i++){
            if (xts[i])
                xml_free(xts[i]);
        }
        free(xts);
    }
    if (nsc)
        cvec_free(nsc);
    if (cbret)
        cbuf_free(cbret);
    if (xcfg)
        xml_free(xcfg);
    if (xerr)
        xml_free(xerr);
    if (cb)
        cbuf_free(cb);
    if (h)
        clixon_handle_exit(h);
    return retval;
}
