name: Clixon-util CI

on:
  push:
    branches:
       - main
       - test-actions
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 4 * * 6'     # Run every Saturday morning

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
# NATIVE BUILD and TEST
    - name: install cligen native
      run: (git clone https://github.com/clicon/cligen.git && cd cligen && ./configure && make && sudo make install)
    - name: install ssl, nghttp2, curl
      run: sudo apt install -y libssl-dev libnghttp2-dev libcurl4-openssl-dev
    - name: install clixon native
      run: (git clone https://github.com/clicon/clixon.git && cd clixon && ./configure && make && sudo make install)
    - name: configure
      run: ./configure
    - name: make and install on host
      run: make && sudo make install && sudo ldconfig
